services:
  top-api:
    image: ghcr.io/yurysidyakin/top-api:main
    container_name: top-api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env:ro
    networks:
      - mongo_default

networks:
  mongo_default:
    external: true
