version: '3.8'
services:
  top-api:
    image: docker pull ghcr.io/yurysidyakin/top-api:8a34aca64dba1876d65311e109e8192681deeb66
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - mongo_network
networks:
  mongo_network:
    name: mongo_default
    external: true
