version: '3.8'
services:
  top-api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - mongo_network
networks:
  mongo_network:
    name: mongo_default
    external: true
